### ISSUE TITLE
Conflict with SelectUpload in CWP install

### ISSUE THREAD

**Issue by creativenz** [dynamic/silverstripe-flexslider#98] opened 2017-03-09 20:28 UTC
Using the [CWP basic recipe](https://gitlab.cwp.govt.nz/cwp/cwp-recipe-basic/blob/master/composer.json), installation of this module (latest dev/master - 1.0.1) via composer as described in the docs causes the following error:
`Warning at line 52 of ..\selectupload\code\SelectUploadField.php`

Which is the first line of the construct function in SelectUpload
`public function __construct($name, $title = null, \SS_List $items = null) {`

This error appears when trying to open the page type that this extension has been added to. In my case it is HomePage.

**Comment by muskie9** [comment] 2017-03-14 14:30
@creativenz we've released a new tag `1.0.3`. We've updated the cms fields to run of the scaffold set from the `parent::getCMSFields()` call. Could you test with that tag and let us know if it resolves the issue in your installation.

**Comment by creativenz** [comment] 2017-03-14 22:25
@muskie9 I have updated to 1.0.3 and ensured your updates were present in my codebase. Unfortunately the same error appears when I try to access the my HomePage.

Further info I now have a trace of the error: http://pastebin.com/jLWhqaxE

**Comment by muskie9** [comment] 2019-05-08 21:52
Closing as 1 branch is no longer supported, if the issue is still present in newer versions we can re-open.

**Closed by muskie9** 2019-05-08 21:52 UTC
